// Printed by sv2asp.aspfirst from l1.lp -- the ASP is the source; do not edit this file.

module fifo #(
  parameter DEPTH = 4,
  parameter WIDTH = 8
) (
  input logic clk,
  input logic reset_n,
  input logic push,
  input logic [WIDTH-1:0] data_push,
  output logic full,
  input logic pop,
  output logic [WIDTH-1:0] data_pop,
  output logic valid_pop,
  output logic empty
);
  localparam ADDRESS_WIDTH = $clog2(DEPTH);
  localparam POINTER_WIDTH = (ADDRESS_WIDTH+1);
  logic vcc;
  logic [POINTER_WIDTH-1:0] write_pointer;
  logic [POINTER_WIDTH-1:0] read_pointer;
  logic push_accepted;
  logic pop_served;
  logic [POINTER_WIDTH-1:0] wp_plus_one;
  logic [POINTER_WIDTH-1:0] rp_plus_one;
  logic [POINTER_WIDTH-1:0] write_pointer_opposed;
  logic [ADDRESS_WIDTH-1:0] write_address;
  logic [ADDRESS_WIDTH-1:0] read_address;
  logic [WIDTH-1:0] storage [0:DEPTH-1];

  assign vcc = 1'd1;
  logic push_accepted__e0;
  logic push_accepted__e1;
  assign push_accepted__e0 = !full;
  assign push_accepted__e1 = push && push_accepted__e0;
  assign push_accepted = reset_n && push_accepted__e1;
  logic pop_served__e0;
  logic pop_served__e1;
  assign pop_served__e0 = !empty;
  assign pop_served__e1 = pop && pop_served__e0;
  assign pop_served = reset_n && pop_served__e1;
  logic [POINTER_WIDTH-1:0] wp_plus_one__e0;
  assign wp_plus_one__e0 = 1;
  assign wp_plus_one = write_pointer + wp_plus_one__e0;
  logic [POINTER_WIDTH-1:0] rp_plus_one__e0;
  assign rp_plus_one__e0 = 1;
  assign rp_plus_one = read_pointer + rp_plus_one__e0;
  assign empty = read_pointer == write_pointer;
  logic [POINTER_WIDTH-1:0] write_pointer_opposed__e0;
  assign write_pointer_opposed__e0 = DEPTH;
  assign write_pointer_opposed = write_pointer + write_pointer_opposed__e0;
  assign full = read_pointer == write_pointer_opposed;
  assign valid_pop = !empty;
  assign write_address = write_pointer[0+ADDRESS_WIDTH-1:0];
  assign read_address = read_pointer[0+ADDRESS_WIDTH-1:0];
  assign data_pop = storage[read_address];

  always_ff @(posedge clk or negedge reset_n)
    if (!reset_n) write_pointer <= '0;
    else if (push_accepted) write_pointer <= wp_plus_one;

  always_ff @(posedge clk or negedge reset_n)
    if (!reset_n) read_pointer <= '0;
    else if (pop_served) read_pointer <= rp_plus_one;

  always_ff @(posedge clk) if (push_accepted) storage[write_address] <= data_push;
endmodule
