#!/usr/bin/env python3
"""Generate the instruction-fetch miss queue: the design (l1.lp) and its linkage (l1.inv.lp).

THE REGENERATION RUN'S SHAPE (the user's requirements, recorded in the route worklist):

  * PARAMETRIC IN DEPTH. Entry state is LANES over `depth` (`net_lane`/`def_lane`/
    `inst_lane`), so the print carries `#(parameter depth = ...)` and `generate for`
    blocks instead of unrolled `valid_0, valid_1, ...` nets. Everything that scans the
    entries — allocation priority, the demand-first policy, the counts, the output muxes,
    the rotating forward arbiter — is a CHAIN along the lane (`x(I-1)` with a boundary
    member closing each chain), never a Python loop baking the depth in.

  * THE STAGING CONVENTION. Every register `xx` is fed by a combinational `xxM1` net
    carrying its COMPLETE next value with the hold term visible —
    `ite(set, value, xx(I))` — and the flop is simply `xx <= xxM1` (a plain `ff`, or an
    `arff` where reset matters). No write-enable pins hiding the hold inside a primitive.

  * ALL STATE THROUGH THE PRIMITIVES, and every name lowerCamelCase and human.

THE THREE LAYERS, kept apart (methodology, the no-regress chapter):

  CAM     pure comparison: does this slot hold this line?
  POLICY  what an equality MEANS: who allocates, who lifts, whose enquiry goes out, who
          is answered. Every race is decided here, one named net each.
  STATE   the slots, which only hold. Every event reaches them already decided.

THE ARBITER, reformulated for lanes (the one 2-D structure in the first run): the old
rotation compared a binary pointer against every slot constant, an O(depth^2) net square
no lane can express. The regeneration uses the textbook parametric rotating arbiter as
CHAINS: the pointer is a ONE-HOT lane; `thermo(I)` is the thermometer "the pointer is at
or below I" (its lane-0 boundary also absorbs the all-zeros power-on, read as pointer 0);
the first ripe slot AT/AFTER the pointer wins, else the first ripe slot BEFORE it (the
wrap), and the ring closes through the boundary member of the pointer's next-value lane.
Same bounded-rotation guarantee — `RouteLean.Rotation.reaches` is about exactly this
shape — now at every depth.

TWO DECISIONS CARRIED FROM THE FIRST RUN:

  * The two counts are POPCOUNT CHAINS of the valid and in-flight bits, combinational —
    not counter registers. Several prefetch entries can end in one cycle; a counter would
    need a multi-way decrement, a popcount does not care.

  * Acceptance is decided in exactly ONE place, `requestReady`. Nothing else decides
    whether a request is taken.
"""
import argparse
import pathlib


def generate(depth: int, reserve: int, max_fetches: int) -> tuple:
    cw = max(2, (depth + 1).bit_length())        # holds 0..depth
    L, INV = [], []
    def w(*xs): L.extend(xs)

    w(f"% GENERATED by generate.py (depth {depth}, demandReserve {reserve}, "
      f"maxOutstandingFetches {max_fetches}) -- do not edit by hand.",
      "% The instruction-fetch miss queue. An ENTRY IS A LINE: a demand meeting a",
      "% prefetched line LIFTS that entry rather than taking a slot of its own.",
      "module(rvMissq).",
      "",
      "% the parameters: the print carries these as `#(parameter ...)`; the certificate",
      "% runs at the defaults, which are the signature's -- the proven configuration",
      f"param(depth, {depth}).",
      f"param(demandReserve, {reserve}).",
      f"param(maxOutstandingFetches, {max_fetches}).",
      "param(addressWidth, 26).",
      "param(dataWidth, 128).",
      "param(tagWidth, 4).",
      "% countWidth is DERIVED, never independently overridable: an instantiation that",
      "% raised DEPTH and forgot the width would cast DEPTH to fewer bits than it",
      "% needs and every threshold would collapse (the user's review, 2026-08-31)",
      "param(countWidth, log2(add(depth, 1))).",
      "param(top, sub(depth, 1)).",
      "",
      "port(clk, input, 1). port(resetN, input, 1).",
      "port(requestValid, input, 1). port(requestReady, output, 1).",
      "port(requestAddress, input, addressWidth). port(requestTag, input, tagWidth).",
      "port(requestIsDemand, input, 1).",
      "port(redirectValid, input, 1).",
      "port(fetchStall, output, 1).",
      "port(memoryRequestValid, output, 1). port(memoryRequestReady, input, 1).",
      "port(memoryRequestAddress, output, addressWidth).",
      "port(fillValid, input, 1). port(fillAddress, input, addressWidth).",
      "port(fillData, input, dataWidth).",
      "port(forwardValid, output, 1). port(forwardTag, output, tagWidth).",
      "port(forwardData, output, dataWidth).",
      "",
      "% the opaque payloads: tokens, compared and routed, never enumerated",
      "data(requestAddress). data(requestTag). data(fillAddress). data(fillData).",
      "data(memoryRequestAddress). data(forwardTag). data(forwardData).",

      "")

    # ---------------------------------------------------------------- CAM
    w("% the state lanes, DECLARED up front: their logic and flops live in the STATE",
      "% section below, but the CAM and the policy read them",
      "net_lane(valid, depth, 1). net_lane(dem, depth, 1). net_lane(want, depth, 1).",
      "net_lane(infl, depth, 1). net_lane(fill, depth, 1).",
      "net_lane(addr, depth, addressWidth). net_lane(entryTag, depth, tagWidth).",
      "net_lane(line, depth, dataWidth). net_lane(ptrHot, depth, 1).",
      "net_lane(askPtrHot, depth, 1).",
      "")

    w("% ---- CAM: equality, and nothing else -----------------------------------------",
      "net_lane(joinable, depth, 1).",
      "def_lane(joinable, I, logand(valid(I), logor(want(I), infl(I)))).",
      "net_lane(free, depth, 1).",
      "def_lane(free, I, lnot(valid(I))).",
      "net_lane(amatch, depth, 1).",
      "def_lane(amatch, I, logand(joinable(I), eq(addr(I), requestAddress))).",
      "net_lane(fillhit, depth, 1).",
      "def_lane(fillhit, I, logand(logand(fillValid, valid(I)), "
      "logand(infl(I), eq(addr(I), fillAddress)))).",
      "")

    def rot_arbiter(grant, req, adv, ptr, what, why):
        """THE ROTATING ARBITER, written once and instantiated per port: a one-hot
        pointer lane; the thermometer 'the pointer sits at or below I', whose lane-0
        boundary absorbs the all-zeros power-on (read as pointer-at-0); the first
        requesting slot AT/AFTER the pointer wins, else the first BEFORE it (the
        wrap); the ring closes through the pointer-next lane's boundary member. The
        pointer advances to the slot after the grant whenever `adv` fires."""
        P = ptr[0].upper() + ptr[1:]
        w(f"% ---- {what}: {why}",
          f"net_lane({ptr}M1, depth, 1).",
          f"net_lane(hot{P}UpTo, depth, 1).",
          f"def(hot{P}UpTo(0), {ptr}(0)).",
          f"def_lane(hot{P}UpTo, I, logor(hot{P}UpTo(I-1), {ptr}(I))).",
          f"net(none{P}, 1). def(none{P}, lnot(hot{P}UpTo(top))).",
          f"net_lane(thermo{P}, depth, 1).",
          f"def(thermo{P}(0), logor({ptr}(0), none{P})).",
          f"def_lane(thermo{P}, I, logor(thermo{P}(I-1), {ptr}(I))).",
          f"% the first {req} slot AT or AFTER the pointer wins ...",
          f"net_lane({grant}Low, depth, 1).",
          f"def_lane({grant}Low, I, logand({req}(I), thermo{P}(I))).")
        first_of(f"{grant}LowWin", f"{grant}Low", f"{grant}SeenLow",
                 f"{grant}LowWin: the winner in the at-or-after half")
        w(f"net({grant}AnyLow, 1). def({grant}AnyLow, {grant}SeenLow(top)).",
          f"% ... else the first {req} slot BEFORE it (the wrap half)",
          f"net_lane({grant}High, depth, 1).",
          f"def_lane({grant}High, I, logand({req}(I), lnot(thermo{P}(I)))).")
        first_of(f"{grant}HighWin", f"{grant}High", f"{grant}SeenHigh",
                 f"{grant}HighWin: the wrap half's candidate, taken only when the low half is empty")
        w(f"net_lane({grant}, depth, 1).",
          f"def_lane({grant}, I, logor({grant}LowWin(I), "
          f"logand({grant}HighWin(I), lnot({grant}AnyLow)))).",
          f"% the pointer: to the slot after the grant when {adv} fires, else hold;",
          f"% the ring closes through the boundary member",
          f"def({ptr}M1(0), ite({adv}, {grant}(top), {ptr}(0))).",
          f"def_lane({ptr}M1, I, ite({adv}, {grant}(I-1), {ptr}(I))).",
          f"inst_lane(u{P}, arff, depth).",
          f"pin(u{P}, clk, clk). pin(u{P}, rstL, resetN). pin(u{P}, en, one).",
          f"pin(u{P}, d, {ptr}M1). pin(u{P}, q, {ptr}).",
          f"iparam(u{P}, width, 1). iparam(u{P}, reset_value, 0).",
          "")

    def chain_or(name, member, comment=""):
        """A running OR along the lane: name(I) = member(0) || ... || member(I)."""
        w(f"% {comment}" if comment else f"% {name}: a running OR along the lane",
          f"net_lane({name}, depth, 1).",
          f"def({name}(0), {member.replace('(I)', '(0)')}).",
          f"def_lane({name}, I, logor({name}(I-1), {member})).")

    def first_of(name, cond, seen, comment):
        """cond(I) and no earlier slot's cond: the priority chain, written once."""
        chain_or(seen, f"{cond}(I)", f"{seen}: has any slot at or below I got {cond}?")
        w(f"% {comment}",
          f"net_lane({name}, depth, 1).",
          f"def({name}(0), {cond}(0)).",
          f"def_lane({name}, I, logand({cond}(I), lnot({seen}(I-1)))).",
          "")

    # ---------------------------------------------------------------- POLICY
    w("% ---- POLICY: what an equality MEANS. Every race is decided here. --------------")
    chain_or("someMatchUpTo", "amatch(I)", "someMatchUpTo: a joinable entry holds the request's line")
    w("net(someMatch, 1). def(someMatch, someMatchUpTo(top)).")
    chain_or("demMatchUpTo", "logand(amatch(I), dem(I))",
             "demMatchUpTo: that joinable entry is already demanding")
    w("net(matchDem, 1). def(matchDem, demMatchUpTo(top)).",
      "net(isPrefetch, 1). def(isPrefetch, lnot(requestIsDemand)).",
      "% the fetch pipe is stalled by a second demand for a line already demanded: an",
      "% entry holds ONE demand entryTag, so the second cannot merge and must wait",
      "net(repeatDemand, 1). def(repeatDemand, logand(logand(requestValid, "
      "requestIsDemand), matchDem)).",
      "def(fetchStall, repeatDemand).",
      "")

    w("% the two counts: popcount chains, combinational (see the module header)",
      "net_lane(liveCnt, depth, countWidth).",
      "def(liveCnt(0), add(k(0, countWidth), valid(0), countWidth)).",
      "def_lane(liveCnt, I, add(liveCnt(I-1), valid(I), countWidth)).",
      "net(liveCount, countWidth). def(liveCount, liveCnt(top)).",
      "net_lane(inflCnt, depth, countWidth).",
      "% the count is of EXISTING entries in flight: valid-gated, exactly as the",
      "% inFlight window is -- a stale infl bit in an invalid slot is not an entry",
      "% (the user's reset review, 2026-08-31)",
      "net_lane(inflLive, depth, 1).",
      "def_lane(inflLive, I, logand(valid(I), infl(I))).",
      "def(inflCnt(0), add(k(0, countWidth), inflLive(0), countWidth)).",
      "def_lane(inflCnt, I, add(inflCnt(I-1), inflLive(I), countWidth)).",
      "net(inflCount, countWidth). def(inflCount, inflCnt(top)).",
      "% the three thresholds are PARAMETER EXPRESSIONS, never baked numbers -- a",
      "% parameterized module whose compares hard-code the defaults is parameterized",
      "% in name only (the user's review, 2026-08-31)",
      "net(roomForDemand, 1). def(roomForDemand, lt(liveCount, k(depth, countWidth), "
      "countWidth)).",
      "net(roomForPrefetch, 1). def(roomForPrefetch, lt(liveCount, "
      "k(sub(depth, demandReserve), countWidth), countWidth)).",
      "net(fetchLimitAllows, 1). def(fetchLimitAllows, lt(inflCount, "
      "k(maxOutstandingFetches, countWidth), countWidth)).",
      "")

    w("% ACCEPTANCE, decided in exactly one place. A demand may take the reserve; a",
      "% prefetch may not; a repeat demand is never taken. A request that JOINS a line",
      "% already here needs no room at all -- merging and lifting consume no slot.",
      "net(noRoomNeeded, 1). def(noRoomNeeded, someMatch).",
      "net(demandOk, 1). def(demandOk, logand(logand(requestIsDemand, "
      "logor(noRoomNeeded, roomForDemand)), lnot(repeatDemand))).",
      "net(prefetchOk, 1). def(prefetchOk, logand(isPrefetch, "
      "logor(noRoomNeeded, roomForPrefetch))).",
      "def(requestReady, logand(requestValid, logor(demandOk, prefetchOk))).",
      "net(accepted, 1). def(accepted, logand(requestValid, requestReady)).",
      "net(allocating, 1). def(allocating, logand(accepted, lnot(someMatch))).",
      "")

    first_of("firstFree", "free", "seenFree",
             "allocation takes the lowest free slot; a LIFT takes no slot at all")
    w("net_lane(alloc, depth, 1).",
      "def_lane(alloc, I, logand(allocating, firstFree(I))).",
      "net_lane(lift, depth, 1).",
      "def_lane(lift, I, logand(logand(accepted, requestIsDemand), "
      "logand(amatch(I), lnot(dem(I))))).",
      "")

    w("% the enquiry: a demanding entry is served before any prefetching one")
    chain_or("demWaitUpTo", "logand(valid(I), logand(want(I), dem(I)))",
             "demWaitUpTo: some demanding entry still wants its fetch")
    w("net(demWaiting, 1). def(demWaiting, demWaitUpTo(top)).",
      "net_lane(eligible, depth, 1).",
      "def_lane(eligible, I, logand(logand(valid(I), want(I)), "
      "logor(dem(I), lnot(demWaiting)))).")
    chain_or("eligUpTo", "eligible(I)", "eligUpTo: is any slot eligible at all?")
    w("net(enquiryTaken, 1). def(enquiryTaken, logand(memoryRequestValid, "
      "memoryRequestReady)).", "")
    rot_arbiter(grant="ask", req="eligible", adv="enquiryTaken", ptr="askPtrHot",
                what="the enquiry",
                why="rotation on the fetch side too. `choose fairly among eligible\n"
      "% entries` is the askMemory behaviour's stated obligation, and fixed lowest-index\n"
      "% priority starves a high slot exactly as it would on the forward side (the\n"
      "% user's review caught the asymmetry, 2026-08-31)")
    w("def(memoryRequestValid, logand(eligUpTo(top), fetchLimitAllows)).",
      "% the enquiry's address: a selection chain over the asking slot",
      "net_lane(askAddr, depth, addressWidth).",
      "def(askAddr(0), addr(0)).",
      "def_lane(askAddr, I, ite(ask(I), addr(I), askAddr(I-1))).",
      "def(memoryRequestAddress, askAddr(top)).",
      "net_lane(taken, depth, 1).",
      "def_lane(taken, I, logand(logand(memoryRequestValid, memoryRequestReady), "
      "ask(I))).",
      "")

    # ------------------------------------------------------------ the rotating arbiter
    w("% ---- THE ANSWER: one filled demanding entry forwarded per cycle, in ROTATION.",
      "% Fixed priority starves a high slot at depths above four; a rotating pointer",
      "% bounds any slot's wait at `depth` grants, at EVERY depth -- the parametric fact",
      "% is RouteLean.Rotation.reaches. The pointer is ONE-HOT; `thermo` is the",
      "% thermometer 'the pointer sits at or below I', whose lane-0 boundary also",
      "% absorbs the all-zeros power-on (read as: pointer at slot 0).",
      "net_lane(ripe, depth, 1).",
      "def_lane(ripe, I, logand(valid(I), logand(fill(I), dem(I)))).")
    chain_or("anyRipeUpTo", "ripe(I)", "anyRipeUpTo: is anything ready to forward?")
    w("def(forwardValid, anyRipeUpTo(top)).",
      "")
    rot_arbiter(grant="fwd", req="ripe", adv="forwardValid", ptr="ptrHot",
                what="the answer",
                why="one filled demanding entry forwarded per cycle, in rotation.\n"
      "% Fixed priority starves a high slot at depths above four; the rotating\n"
      "% pointer bounds any slot's wait at depth grants, at EVERY depth\n"
      "% (RouteLean.Rotation.reaches)")
    w("% the granted slot's payload, by a selection chain",
      "net_lane(fwdTagSel, depth, tagWidth).",
      "def(fwdTagSel(0), entryTag(0)).",
      "def_lane(fwdTagSel, I, ite(fwd(I), entryTag(I), fwdTagSel(I-1))).",
      "def(forwardTag, fwdTagSel(top)).",
      "net_lane(fwdDataSel, depth, dataWidth).",
      "def(fwdDataSel(0), line(0)).",
      "def_lane(fwdDataSel, I, ite(fwd(I), line(I), fwdDataSel(I-1))).",
      "def(forwardData, fwdDataSel(top)).",
      "")

    w("% an entry ends when it is answered, or when a prefetched line has landed",
      "net_lane(ends, depth, 1).",
      "def_lane(ends, I, logand(valid(I), logor(logand(forwardValid, fwd(I)), "
      "logand(fill(I), lnot(dem(I)))))).",
      "")

    # ---------------------------------------------------------------- STATE, M1-staged
    w("% ---- STATE: the slots. Every register xx is fed by xxM1, its complete next",
      "% value with the hold term VISIBLE, and the flop is xx <= xxM1. --------------",
      "",
      "% valid: set on allocation, cleared on ending, else hold. The one reset register",
      "% per slot -- a slot whose valid is 0 makes every other field invisible.",
      "net_lane(validM1, depth, 1).",
      "def_lane(validM1, I, logor(alloc(I), logand(valid(I), lnot(ends(I))))).",
      "inst_lane(uValid, arff, depth).",
      "pin(uValid, clk, clk). pin(uValid, rstL, resetN). pin(uValid, en, one).",
      "pin(uValid, d, validM1). pin(uValid, q, valid).",
      "iparam(uValid, width, 1). iparam(uValid, reset_value, 0).",
      "net(one, 1). def(one, k(1, 1)).",
      "",
      "% demanding: set by a demand allocation or a lift, cleared by redirect or ending",
      "net_lane(demM1, depth, 1).",
      "def_lane(demM1, I, logor(logor(logand(alloc(I), requestIsDemand), lift(I)), "
      "logand(dem(I), lnot(logor(alloc(I), logor(redirectValid, ends(I))))))).",
      "inst_lane(uDem, ff, depth).",
      "pin(uDem, clk, clk). pin(uDem, en, one). pin(uDem, d, demM1). pin(uDem, q, dem).",
      "iparam(uDem, width, 1).",
      "",
      "% wantsFetch: set on allocation, cleared when the enquiry is taken or on ending",
      "net_lane(wantM1, depth, 1).",
      "def_lane(wantM1, I, logor(alloc(I), "
      "logand(want(I), lnot(logor(taken(I), ends(I)))))).",
      "inst_lane(uWant, ff, depth).",
      "pin(uWant, clk, clk). pin(uWant, en, one). pin(uWant, d, wantM1). "
      "pin(uWant, q, want).",
      "iparam(uWant, width, 1).",
      "",
      "% inFlight: set when the enquiry is taken, cleared by the fill, ending, or a",
      "% fresh allocation of the slot",
      "net_lane(inflM1, depth, 1).",
      "def_lane(inflM1, I, logor(taken(I), "
      "logand(infl(I), lnot(logor(fillhit(I), logor(ends(I), alloc(I))))))).",
      "inst_lane(uInfl, ff, depth).",
      "pin(uInfl, clk, clk). pin(uInfl, en, one). pin(uInfl, d, inflM1). "
      "pin(uInfl, q, infl).",
      "iparam(uInfl, width, 1).",
      "",
      "% filled: set by the fill, cleared by ending or a fresh allocation",
      "net_lane(fillM1, depth, 1).",
      "def_lane(fillM1, I, logor(fillhit(I), "
      "logand(fill(I), lnot(logor(ends(I), alloc(I)))))).",
      "inst_lane(uFill, ff, depth).",
      "pin(uFill, clk, clk). pin(uFill, en, one). pin(uFill, d, fillM1). "
      "pin(uFill, q, fill).",
      "iparam(uFill, width, 1).",
      "",
      "% the payloads. The address never changes while the entry lives -- an entry IS a",
      "% line. The entryTag follows a lift: the new demand's entryTag replaces the prefetch's.",
      "net_lane(addrM1, depth, addressWidth).",
      "def_lane(addrM1, I, ite(alloc(I), requestAddress, addr(I))).",
      "inst_lane(uAddr, ff, depth).",
      "pin(uAddr, clk, clk). pin(uAddr, en, one). pin(uAddr, d, addrM1). "
      "pin(uAddr, q, addr).",
      "iparam(uAddr, width, addressWidth).",
      "",
      "net_lane(entryTagM1, depth, tagWidth).",
      "def_lane(entryTagM1, I, ite(logor(alloc(I), lift(I)), requestTag, entryTag(I))).",
      "inst_lane(uEntryTag, ff, depth).",
      "pin(uEntryTag, clk, clk). pin(uEntryTag, en, one). pin(uEntryTag, d, entryTagM1). pin(uEntryTag, q, entryTag).",
      "iparam(uEntryTag, width, tagWidth).",
      "",
      "net_lane(lineM1, depth, dataWidth).",
      "def_lane(lineM1, I, ite(fillhit(I), fillData, line(I))).",
      "inst_lane(uLine, ff, depth).",
      "pin(uLine, clk, clk). pin(uLine, en, one). pin(uLine, d, lineM1). "
      "pin(uLine, q, line).",
      "iparam(uLine, width, dataWidth).",
      "",
      "")

    w("% the slot payload lanes and everything that routes them are token nets too;",
      "% data() on a lane declares every member. Declared LAST: a lane must exist",
      "% before it can be called data.",
      "data(addr). data(entryTag). data(line).",
      "data(addrM1). data(entryTagM1). data(lineM1).",
      "data(askAddr). data(fwdTagSel). data(fwdDataSel).",
      "")

    # ---------------------------------------------------------------- the linkage
    S = range(depth)
    INV += ["% GENERATED by generate.py -- l1's LINKAGE: the contract's windows mounted on",
            "% THIS design's state. Derived views, head at T, no state of their own. The",
            "% linkage is per-configuration (the certificate runs at the defaults), so it",
            "% names the unrolled lane members.", ""]
    for i in S:
        INV += [f"entryExists({i}, T) :- val(valid({i}), 1, T).",
                f"entryAddress({i}, A, T) :- val(addr({i}), A, T), val(valid({i}), 1, T).",
                f"entryTag({i}, X, T) :- val(entryTag({i}), X, T), val(valid({i}), 1, T).",
                f"demanding({i}, T) :- val(dem({i}), 1, T), val(valid({i}), 1, T).",
                f"wantsFetch({i}, T) :- val(want({i}), 1, T), val(valid({i}), 1, T).",
                f"inFlight({i}, T) :- val(infl({i}), 1, T), val(valid({i}), 1, T).",
                f"filled({i}, T) :- val(fill({i}), 1, T), val(valid({i}), 1, T).",
                f"lineData({i}, V, T) :- val(line({i}), V, T), val(fill({i}), 1, T), "
                f"val(valid({i}), 1, T).",
                f"forwarded({i}, T) :- val(fwd({i}), 1, T), val(forwardValid, 1, T).",
                f"corresponds(fwd, {i}, T) :- forwarded({i}, T)."]
    INV += ["% THE SAME STATE under the second producer's names: the FV stand-in's",
            "% contract (specFv.lp) spells existence entryValid and the grant forwardOf.",
            "% Two vocabularies, one flop -- derived views cannot disagree."]
    for i in S:
        INV += [f"entryValid({i}, T) :- entryExists({i}, T).",
                f"forwardOf({i}, T) :- forwarded({i}, T)."]
    INV += ["% the two counts are combinational nets, not registers -- a window is a",
            "% derived view and does not care which",
            "liveEntries(N, T) :- val(liveCount, N, T).",
            "inFlightCount(N, T) :- val(inflCount, N, T)."]
    return "\n".join(L) + "\n", "\n".join(INV) + "\n"


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--depth", type=int, default=4)
    ap.add_argument("--reserve", type=int, default=1)
    ap.add_argument("--fetches", type=int, default=2)
    ap.add_argument("-o", default=str(pathlib.Path(__file__).parent))
    a = ap.parse_args()
    design, inv = generate(a.depth, a.reserve, a.fetches)
    d = pathlib.Path(a.o)
    (d / "l1.lp").write_text(design)
    (d / "l1.inv.lp").write_text(inv)
    print(f"wrote l1.lp ({len(design.splitlines())} lines) and "
          f"l1.inv.lp ({len(inv.splitlines())} lines), depth {a.depth}")
