// Printed by sv2asp.aspfirst from l1.lp -- the ASP is the source; do not edit this file.

module rvMissq #(
  parameter DEPTH = 4,
  parameter DEMANDRESERVE = 1,
  parameter MAXOUTSTANDINGFETCHES = 2,
  parameter ADDRESSWIDTH = 26,
  parameter DATAWIDTH = 128,
  parameter TAGWIDTH = 4
) (
  input logic clk,
  input logic resetN,
  input logic requestValid,
  output logic requestReady,
  input logic [ADDRESSWIDTH-1:0] requestAddress,
  input logic [TAGWIDTH-1:0] requestTag,
  input logic requestIsDemand,
  input logic redirectValid,
  output logic fetchStall,
  output logic memoryRequestValid,
  input logic memoryRequestReady,
  output logic [ADDRESSWIDTH-1:0] memoryRequestAddress,
  input logic fillValid,
  input logic [ADDRESSWIDTH-1:0] fillAddress,
  input logic [DATAWIDTH-1:0] fillData,
  output logic forwardValid,
  output logic [TAGWIDTH-1:0] forwardTag,
  output logic [DATAWIDTH-1:0] forwardData
);
  localparam COUNTWIDTH = $clog2((DEPTH+1));
  localparam TOP = (DEPTH-1);
  logic someMatch;
  logic matchDem;
  logic isPrefetch;
  logic repeatDemand;
  logic [COUNTWIDTH-1:0] liveCount;
  logic [COUNTWIDTH-1:0] inflCount;
  logic roomForDemand;
  logic roomForPrefetch;
  logic fetchLimitAllows;
  logic noRoomNeeded;
  logic demandOk;
  logic prefetchOk;
  logic accepted;
  logic allocating;
  logic demWaiting;
  logic enquiryTaken;
  logic noneAskPtrHot;
  logic askAnyLow;
  logic nonePtrHot;
  logic fwdAnyLow;
  logic one;
  logic [DEPTH-1:0] valid;
  logic [DEPTH-1:0] dem;
  logic [DEPTH-1:0] want;
  logic [DEPTH-1:0] infl;
  logic [DEPTH-1:0] fill;
  logic [DEPTH-1:0][ADDRESSWIDTH-1:0] addr;
  logic [DEPTH-1:0][TAGWIDTH-1:0] entryTag;
  logic [DEPTH-1:0][DATAWIDTH-1:0] line;
  logic [DEPTH-1:0] ptrHot;
  logic [DEPTH-1:0] askPtrHot;
  logic [DEPTH-1:0] joinable;
  logic [DEPTH-1:0] free;
  logic [DEPTH-1:0] amatch;
  logic [DEPTH-1:0] fillhit;
  logic [DEPTH-1:0] someMatchUpTo;
  logic [DEPTH-1:0] demMatchUpTo;
  logic [DEPTH-1:0][COUNTWIDTH-1:0] liveCnt;
  logic [DEPTH-1:0][COUNTWIDTH-1:0] inflCnt;
  logic [DEPTH-1:0] inflLive;
  logic [DEPTH-1:0] seenFree;
  logic [DEPTH-1:0] firstFree;
  logic [DEPTH-1:0] alloc;
  logic [DEPTH-1:0] lift;
  logic [DEPTH-1:0] demWaitUpTo;
  logic [DEPTH-1:0] eligible;
  logic [DEPTH-1:0] eligUpTo;
  logic [DEPTH-1:0] askPtrHotM1;
  logic [DEPTH-1:0] hotAskPtrHotUpTo;
  logic [DEPTH-1:0] thermoAskPtrHot;
  logic [DEPTH-1:0] askLow;
  logic [DEPTH-1:0] askSeenLow;
  logic [DEPTH-1:0] askLowWin;
  logic [DEPTH-1:0] askHigh;
  logic [DEPTH-1:0] askSeenHigh;
  logic [DEPTH-1:0] askHighWin;
  logic [DEPTH-1:0] ask;
  logic [DEPTH-1:0][ADDRESSWIDTH-1:0] askAddr;
  logic [DEPTH-1:0] taken;
  logic [DEPTH-1:0] ripe;
  logic [DEPTH-1:0] anyRipeUpTo;
  logic [DEPTH-1:0] ptrHotM1;
  logic [DEPTH-1:0] hotPtrHotUpTo;
  logic [DEPTH-1:0] thermoPtrHot;
  logic [DEPTH-1:0] fwdLow;
  logic [DEPTH-1:0] fwdSeenLow;
  logic [DEPTH-1:0] fwdLowWin;
  logic [DEPTH-1:0] fwdHigh;
  logic [DEPTH-1:0] fwdSeenHigh;
  logic [DEPTH-1:0] fwdHighWin;
  logic [DEPTH-1:0] fwd;
  logic [DEPTH-1:0][TAGWIDTH-1:0] fwdTagSel;
  logic [DEPTH-1:0][DATAWIDTH-1:0] fwdDataSel;
  logic [DEPTH-1:0] ends;
  logic [DEPTH-1:0] validM1;
  logic [DEPTH-1:0] demM1;
  logic [DEPTH-1:0] wantM1;
  logic [DEPTH-1:0] inflM1;
  logic [DEPTH-1:0] fillM1;
  logic [DEPTH-1:0][ADDRESSWIDTH-1:0] addrM1;
  logic [DEPTH-1:0][TAGWIDTH-1:0] entryTagM1;
  logic [DEPTH-1:0][DATAWIDTH-1:0] lineM1;

  assign someMatchUpTo[0] = amatch[0];
  assign someMatch = someMatchUpTo[TOP];
  assign demMatchUpTo[0] = amatch[0] & dem[0];
  assign matchDem = demMatchUpTo[TOP];
  assign isPrefetch = ~requestIsDemand;
  assign repeatDemand = (requestValid & requestIsDemand) & matchDem;
  assign fetchStall = repeatDemand;
  assign liveCnt[0] = COUNTWIDTH'(0) + valid[0];
  assign liveCount = liveCnt[TOP];
  assign inflCnt[0] = COUNTWIDTH'(0) + inflLive[0];
  assign inflCount = inflCnt[TOP];
  assign roomForDemand = liveCount < COUNTWIDTH'(DEPTH);
  assign roomForPrefetch = liveCount < COUNTWIDTH'((DEPTH-DEMANDRESERVE));
  assign fetchLimitAllows = inflCount < COUNTWIDTH'(MAXOUTSTANDINGFETCHES);
  assign noRoomNeeded = someMatch;
  assign demandOk = (requestIsDemand & (noRoomNeeded | roomForDemand)) & (~repeatDemand);
  assign prefetchOk = isPrefetch & (noRoomNeeded | roomForPrefetch);
  assign requestReady = requestValid & (demandOk | prefetchOk);
  assign accepted = requestValid & requestReady;
  assign allocating = accepted & (~someMatch);
  assign seenFree[0] = free[0];
  assign firstFree[0] = free[0];
  assign demWaitUpTo[0] = valid[0] & (want[0] & dem[0]);
  assign demWaiting = demWaitUpTo[TOP];
  assign eligUpTo[0] = eligible[0];
  assign enquiryTaken = memoryRequestValid & memoryRequestReady;
  assign hotAskPtrHotUpTo[0] = askPtrHot[0];
  assign noneAskPtrHot = ~hotAskPtrHotUpTo[TOP];
  assign thermoAskPtrHot[0] = askPtrHot[0] | noneAskPtrHot;
  assign askSeenLow[0] = askLow[0];
  assign askLowWin[0] = askLow[0];
  assign askAnyLow = askSeenLow[TOP];
  assign askSeenHigh[0] = askHigh[0];
  assign askHighWin[0] = askHigh[0];
  assign askPtrHotM1[0] = enquiryTaken ? ask[TOP] : askPtrHot[0];
  assign memoryRequestValid = eligUpTo[TOP] & fetchLimitAllows;
  assign askAddr[0] = addr[0];
  assign memoryRequestAddress = askAddr[TOP];
  assign anyRipeUpTo[0] = ripe[0];
  assign forwardValid = anyRipeUpTo[TOP];
  assign hotPtrHotUpTo[0] = ptrHot[0];
  assign nonePtrHot = ~hotPtrHotUpTo[TOP];
  assign thermoPtrHot[0] = ptrHot[0] | nonePtrHot;
  assign fwdSeenLow[0] = fwdLow[0];
  assign fwdLowWin[0] = fwdLow[0];
  assign fwdAnyLow = fwdSeenLow[TOP];
  assign fwdSeenHigh[0] = fwdHigh[0];
  assign fwdHighWin[0] = fwdHigh[0];
  assign ptrHotM1[0] = forwardValid ? fwd[TOP] : ptrHot[0];
  assign fwdTagSel[0] = entryTag[0];
  assign forwardTag = fwdTagSel[TOP];
  assign fwdDataSel[0] = line[0];
  assign forwardData = fwdDataSel[TOP];
  assign one = 1'd1;
  generate for (genvar i = 0; i < DEPTH; i++) begin : g_joinable
    assign joinable[i] = valid[i] & (want[i] | infl[i]);
    assign free[i] = ~valid[i];
    assign amatch[i] = joinable[i] & (addr[i] == requestAddress);
    assign fillhit[i] = (fillValid & valid[i]) & (infl[i] & (addr[i] == fillAddress));
  end endgenerate
  generate for (genvar i = 1; i < DEPTH; i++) begin : g_someMatchUpTo
    assign someMatchUpTo[i] = someMatchUpTo[i-1] | amatch[i];
    assign demMatchUpTo[i] = demMatchUpTo[i-1] | (amatch[i] & dem[i]);
    assign liveCnt[i] = liveCnt[i-1] + valid[i];
  end endgenerate
  generate for (genvar i = 0; i < DEPTH; i++) begin : g_inflLive
    assign inflLive[i] = valid[i] & infl[i];
  end endgenerate
  generate for (genvar i = 1; i < DEPTH; i++) begin : g_inflCnt
    assign inflCnt[i] = inflCnt[i-1] + inflLive[i];
    assign seenFree[i] = seenFree[i-1] | free[i];
    assign firstFree[i] = free[i] & (~seenFree[i-1]);
  end endgenerate
  generate for (genvar i = 0; i < DEPTH; i++) begin : g_alloc
    assign alloc[i] = allocating & firstFree[i];
    assign lift[i] = (accepted & requestIsDemand) & (amatch[i] & (~dem[i]));
  end endgenerate
  generate for (genvar i = 1; i < DEPTH; i++) begin : g_demWaitUpTo
    assign demWaitUpTo[i] = demWaitUpTo[i-1] | (valid[i] & (want[i] & dem[i]));
  end endgenerate
  generate for (genvar i = 0; i < DEPTH; i++) begin : g_eligible
    assign eligible[i] = (valid[i] & want[i]) & (dem[i] | (~demWaiting));
  end endgenerate
  generate for (genvar i = 1; i < DEPTH; i++) begin : g_eligUpTo
    assign eligUpTo[i] = eligUpTo[i-1] | eligible[i];
    assign hotAskPtrHotUpTo[i] = hotAskPtrHotUpTo[i-1] | askPtrHot[i];
    assign thermoAskPtrHot[i] = thermoAskPtrHot[i-1] | askPtrHot[i];
  end endgenerate
  generate for (genvar i = 0; i < DEPTH; i++) begin : g_askLow
    assign askLow[i] = eligible[i] & thermoAskPtrHot[i];
  end endgenerate
  generate for (genvar i = 1; i < DEPTH; i++) begin : g_askSeenLow
    assign askSeenLow[i] = askSeenLow[i-1] | askLow[i];
    assign askLowWin[i] = askLow[i] & (~askSeenLow[i-1]);
  end endgenerate
  generate for (genvar i = 0; i < DEPTH; i++) begin : g_askHigh
    assign askHigh[i] = eligible[i] & (~thermoAskPtrHot[i]);
  end endgenerate
  generate for (genvar i = 1; i < DEPTH; i++) begin : g_askSeenHigh
    assign askSeenHigh[i] = askSeenHigh[i-1] | askHigh[i];
    assign askHighWin[i] = askHigh[i] & (~askSeenHigh[i-1]);
  end endgenerate
  generate for (genvar i = 0; i < DEPTH; i++) begin : g_ask
    assign ask[i] = askLowWin[i] | (askHighWin[i] & (~askAnyLow));
  end endgenerate
  generate for (genvar i = 1; i < DEPTH; i++) begin : g_askPtrHotM1
    assign askPtrHotM1[i] = enquiryTaken ? ask[i-1] : askPtrHot[i];
    assign askAddr[i] = ask[i] ? addr[i] : askAddr[i-1];
  end endgenerate
  generate for (genvar i = 0; i < DEPTH; i++) begin : g_taken
    assign taken[i] = (memoryRequestValid & memoryRequestReady) & ask[i];
    assign ripe[i] = valid[i] & (fill[i] & dem[i]);
  end endgenerate
  generate for (genvar i = 1; i < DEPTH; i++) begin : g_anyRipeUpTo
    assign anyRipeUpTo[i] = anyRipeUpTo[i-1] | ripe[i];
    assign hotPtrHotUpTo[i] = hotPtrHotUpTo[i-1] | ptrHot[i];
    assign thermoPtrHot[i] = thermoPtrHot[i-1] | ptrHot[i];
  end endgenerate
  generate for (genvar i = 0; i < DEPTH; i++) begin : g_fwdLow
    assign fwdLow[i] = ripe[i] & thermoPtrHot[i];
  end endgenerate
  generate for (genvar i = 1; i < DEPTH; i++) begin : g_fwdSeenLow
    assign fwdSeenLow[i] = fwdSeenLow[i-1] | fwdLow[i];
    assign fwdLowWin[i] = fwdLow[i] & (~fwdSeenLow[i-1]);
  end endgenerate
  generate for (genvar i = 0; i < DEPTH; i++) begin : g_fwdHigh
    assign fwdHigh[i] = ripe[i] & (~thermoPtrHot[i]);
  end endgenerate
  generate for (genvar i = 1; i < DEPTH; i++) begin : g_fwdSeenHigh
    assign fwdSeenHigh[i] = fwdSeenHigh[i-1] | fwdHigh[i];
    assign fwdHighWin[i] = fwdHigh[i] & (~fwdSeenHigh[i-1]);
  end endgenerate
  generate for (genvar i = 0; i < DEPTH; i++) begin : g_fwd
    assign fwd[i] = fwdLowWin[i] | (fwdHighWin[i] & (~fwdAnyLow));
  end endgenerate
  generate for (genvar i = 1; i < DEPTH; i++) begin : g_ptrHotM1
    assign ptrHotM1[i] = forwardValid ? fwd[i-1] : ptrHot[i];
    assign fwdTagSel[i] = fwd[i] ? entryTag[i] : fwdTagSel[i-1];
    assign fwdDataSel[i] = fwd[i] ? line[i] : fwdDataSel[i-1];
  end endgenerate
  generate for (genvar i = 0; i < DEPTH; i++) begin : g_ends
    assign ends[i] = valid[i] & ((forwardValid & fwd[i]) | (fill[i] & (~dem[i])));
    assign validM1[i] = alloc[i] | (valid[i] & (~ends[i]));
    assign demM1[i] = ((alloc[i] & requestIsDemand) | lift[i]) | (dem[i] & (~(alloc[i] | (redirectValid | ends[i]))));
    assign wantM1[i] = alloc[i] | (want[i] & (~(taken[i] | ends[i])));
    assign inflM1[i] = taken[i] | (infl[i] & (~(fillhit[i] | (ends[i] | alloc[i]))));
    assign fillM1[i] = fillhit[i] | (fill[i] & (~(ends[i] | alloc[i])));
    assign addrM1[i] = alloc[i] ? requestAddress : addr[i];
    assign entryTagM1[i] = (alloc[i] | lift[i]) ? requestTag : entryTag[i];
    assign lineM1[i] = fillhit[i] ? fillData : line[i];
  end endgenerate

  generate for (genvar i = 0; i < DEPTH; i++) begin : g_uAskPtrHot
    always_ff @(posedge clk or negedge resetN)
      if (!resetN) askPtrHot[i] <= 1'd0;
      else askPtrHot[i] <= askPtrHotM1[i];
    always_ff @(posedge clk or negedge resetN)
      if (!resetN) ptrHot[i] <= 1'd0;
      else ptrHot[i] <= ptrHotM1[i];
    always_ff @(posedge clk or negedge resetN)
      if (!resetN) valid[i] <= 1'd0;
      else valid[i] <= validM1[i];
    always_ff @(posedge clk)
      dem[i] <= demM1[i];
    always_ff @(posedge clk)
      want[i] <= wantM1[i];
    always_ff @(posedge clk)
      infl[i] <= inflM1[i];
    always_ff @(posedge clk)
      fill[i] <= fillM1[i];
    always_ff @(posedge clk)
      addr[i] <= addrM1[i];
    always_ff @(posedge clk)
      entryTag[i] <= entryTagM1[i];
    always_ff @(posedge clk)
      line[i] <= lineM1[i];
  end endgenerate
endmodule
