"""Print an ASP-first design as SystemVerilog.

WIDTH POLICY (the load-bearing decision -- risk R1 of the plan). SystemVerilog sizes an operand
by its CONTEXT (the widest operand and the assignment target together), so a nested expression
printed inline can be evaluated at a width the author never wrote. Every non-leaf operand is
therefore printed as its OWN typed wire (`<lhs>__eK`, SSA), so each `assign` is `leaf op leaf`
whose context width is exactly the ASP term's `W` (the lint guarantees operands are no wider
than their op, and a def's width equals its net's). Where SV would sign-extend on its own
(`sext`, `ashr`, signed compares/division) the operand is first widened to the op width by an
explicit zero-extending wire, so the sign bit is the one the `@func` reads.

STATE. `--mode behav` prints `always_ff` blocks with the shape the translator recognises for an
async-reset register (`if (!rst) q <= RV; else if (en) q <= d;`); `--mode cells` instantiates the
`FF` / `ARFF` cells of `lib/aspfirst/cells_sim.sv` (same interfaces as
`examples/rtl2asp/primitives_demo/stubs/cells.sv`, with behavioural bodies so Icarus can run them; sv2asp
lowers them from its registry by NAME). A memory (`spram`) is always behavioural. An ENUM-typed
register is always behavioural (a `logic` cell port cannot drive an enum variable without a
cast; the tag is what the ASP carries).

GUARDED RULES. A net defined by comb rules becomes an `always_comb` if/else-if chain, one arm per
rule in authoring order. The LAST arm is printed as a bare `else` only when the arms are PROVEN
total for that head (`totality_certificate` -- a static clingo check with the guarded signals
free over their domains); otherwise every arm keeps its condition and there is no default, so a
missing case reaches sv2asp as an incomplete `always_comb` and fails LOUDLY there instead of
becoming a silent latch or an invented value."""
from __future__ import annotations

import pathlib
import re
import subprocess
import tempfile

from .libgen import LIB_DIR
from .load import is_var, term_to_str
from .lanes import axes_of, member, parse_ref
from .model import Design, Rule

HEADER = "// Printed by sv2asp.aspfirst from {src} -- the ASP is the source; do not edit this file.\n"


class PrintError(Exception):
    pass


#: the operators printed as ONE SV binary operator between two leaves (module-level so a test can
#: sabotage one and prove the round trip notices)
BIN_OPS = {"add": "+", "sub": "-", "mul": "*", "and": "&", "or": "|", "xor": "^",
           "shl": "<<", "shr": ">>", "idiv": "/", "imod": "%",
           "lt": "<", "le": "<=", "gt": ">", "ge": ">=", "eq": "==", "ne": "!=",
           # logand/logor print BITWISE: the authoring nets are 1-bit, where & and | are
           # the same functions -- and the round-trip translator's lane machinery lowers
           # bitwise trees where a &&-tree on a lane target is a named refusal (found by
           # the regeneration run's human-shaped print, 2026-08-31)
           "logand": "&", "logor": "|"}


# ---------------------------------------------------------------------------------------------
# widths
# ---------------------------------------------------------------------------------------------

def enum_tname(net: str) -> str:
    """The SystemVerilog TYPE name for the enum whose members `enum_member(net, ...)` declare.

    `d.enums` is keyed by the NET, and the printer used that key as the typedef name -- so
    `typedef enum ... st;` collided with `logic [1:0] st;` and iverilog refused the file at
    the declaration. Everything else about named states already worked (an enum-typed
    intermediate prints as `st stM1;`, its ternary as `st'(d ? one : none)`, a compare as
    `st == two`); one block fell back to numeric encodings in its RTL for want of this
    suffix (G21, 2026-09-02). The ASP-side spelling `enum(st)` is unchanged.
    """
    return f"{net}_t"


def enum_width(members: list) -> int:
    mx = max(v for _, v in members)
    return max(1, mx.bit_length())


def width_of(d: Design, t) -> object:
    """Result width of a term: an int, or ("enum", E) for a tag / enum net."""
    if isinstance(t, str):
        lm = _lane_member(d, t)
        if lm is not None:
            return d.raw.lane_w.get(lm[0], d.lanes[lm[0]][1]) if d.raw is not None else d.lanes[lm[0]][1]
        if d.raw is not None and (t in d.raw.net_w or t in d.raw.port_w):
            return d.raw.net_w.get(t, d.raw.port_w.get(t))
        w = d.width_of(t)
        if w is None:
            raise PrintError(f"undeclared net {t}")
        return w
    op = t[0]
    if op == "k":
        return t[2]
    if op == "tag":
        for e, ms in d.enums.items():
            if any(l == t[1] for l, _ in ms):
                return ("enum", e)
        raise PrintError(f"unknown tag {t[1]}")
    if op in ("add", "sub", "mul", "and", "or", "xor", "shl", "shr", "ashr", "idiv", "imod",
              "sidiv", "simod", "sext", "slc"):
        return t[-1]
    if op in ("bnot", "neg"):
        return t[2]
    if op == "bit":
        return 1
    if op == "cat":
        return t[2] + t[4] if _isint(t[2]) and _isint(t[4]) else ("add", t[2], t[4])
    if op == "pack":                         # the whole lane: every member side by side
        n, w, _dir = d.lanes[t[1]]
        return n * w if isinstance(n, int) and isinstance(w, int) else ("mul", n, w)
    if op == "mrd":                          # a flop-array read is one CELL: the array's width
        for i in d.insts:
            if i.name == t[1]:
                return i.iparams.get("width")
        for m, (_dep, w) in getattr(d, "arch_mems", {}).items():
            if m == t[1]:
                return w
        raise PrintError(f"mrd of an undeclared array {t[1]}")
    if op in ("eq", "ne", "lt", "le", "gt", "ge", "slt", "sle", "sgt", "sge", "logand", "logor",
              "lnot", "ror", "rand", "rxor", "rnand", "rnor", "rxnor", "parity"):
        return 1
    if op == "popcnt":
        return t[2]
    if op == "clz":
        raise PrintError(
            "clz has no print form yet. It is wired for AUTHORING and LINTING only, because there is no SystemVerilog construct for a leading-zero count -- lowering one means synthesising a priority encoder, a design decision nothing has needed yet. Until then a design that needs an LZC declares it as a CONTRACT-ONLY submodule and is proven from its contract; the print gives it as an interface stub. See notes/WORKLIST_SPEC2RTL.md.")
    if op == "ite":
        return width_of(d, t[2])
    raise PrintError(f"unknown operator {op}")


def _isint(w) -> bool:
    return isinstance(w, int)




def _param_names(t, acc: set) -> set:
    """Every parameter NAME a parameter expression mentions (the operator head is not a name)."""
    if isinstance(t, str):
        acc.add(t)
    elif isinstance(t, tuple):
        for a in t[1:]:
            _param_names(a, acc)
    return acc


def _split_params(d, raw):
    """(header, body) derived parameters.

    A derived parameter goes in the PARAMETER PORT LIST only when a PORT declaration references it:
    there, a body `localparam` would be a declaration after use and will not elaborate
    (`output logic [CW-1:0] lz` with `localparam CW` below the port list). Everything else stays in
    the body, so a module whose ports need none prints exactly as it did before this rule existed.
    Closed transitively -- a needed derived parameter may be defined in terms of another."""
    numeric = [(k, v) for k, v in d.param_exprs.items() if isinstance(v, int)] if raw is not None else []
    derived = [(k, v) for k, v in d.param_exprs.items() if not isinstance(v, int)] if raw is not None else []
    if not derived:
        return numeric, [], []
    refs: set = set()
    for prt in d.ports:
        _param_names(raw.port_w.get(prt.name, prt.width), refs)
    for ln, (N, W, dr) in d.lanes.items():
        if dr:
            _param_names(raw.lane_n.get(ln, N), refs)
            _param_names(raw.lane_w.get(ln, W), refs)
    dmap = dict(derived)
    need: set = set()
    stack = [x for x in refs if x in dmap]
    while stack:
        k = stack.pop()
        if k in need:
            continue
        need.add(k)
        stack.extend(x for x in _param_names(dmap[k], set()) if x in dmap)
    return numeric, [kv for kv in derived if kv[0] in need], [kv for kv in derived if kv[0] not in need]


def _lane_member(d: Design, name: str):
    """(base, index) if `name` is a lane member `x(3)` / a rolled ref `x(I)`, `x(I-1)` /
    a WRAPPING ref `x(I-16 \\ 256)`, else None. A wrap's index is pre-rendered to the SV
    expression of its load-time meaning, (I//B)*B + ((I%B)+k) mod B -- with the offset
    normalised non-negative so SV's % (remainder, like clingo's \\) agrees with the wrap --
    and simplified to a plain ring (I+k)%B when B is the lane's whole extent. Without this
    the toroid's neighbour refs printed as raw ASP terms inside the generate body (found by
    ve144_conwaylife's round trip: `assign up[i] = q(I-16 \\ 256);`).
    """
    r = parse_ref(name)
    if not (r and r.base in d.lanes):
        return None
    axes = axes_of(d.lanes, r.base)
    if len(r.idx) != len(axes):
        return None
    if len(axes) > 1:
        # a MULTI-AXIS member / rolled reference: each axis rendered as the 1-D rule renders
        # its one axis, joined as `x[r][c]` (2026-09-03)
        raw_axes = d.raw.lane_axes.get(r.base) if d.raw is not None else None
        parts = []
        for k, ix in enumerate(r.idx):
            ext = axes[k]
            ext_txt = (str(raw_axes[k]).upper() if raw_axes is not None and not isinstance(raw_axes[k], int) else str(ext))
            parts.append(_axis_sv(d, ix, ext, ext_txt))
        return r.base, "][".join(parts)
    base, ix = r.base, r.idx[0]
    mod = ix.mod
    if ix.is_const:
        return base, str(ix.const)
    if mod is None and not ix.off:
        # A genvar prints lowercase (`x[i]`); a module PARAMETER prints uppercase, matching the
        # localparam the print declares (`x[TOP]`); a literal is left alone.
        return base, ix.var.upper() if ix.var in d.params else ix.var.lower()
    if mod is None:
        return base, f"{ix.var.lower()}{ix.off}"        # `x[i-1]` -- the offset is a number here
    var = ix.var.lower()
    # a NUMBER prints as itself; a PARAMETER prints as the localparam the module declares, so
    # the generate body is parametric where the offsets are -- `q[((i + (CELLS - SIDE)) % CELLS)]`
    # rather than a 240 baked at one size (G28, 2026-09-02)
    B = int(mod) if mod.isdigit() else d.params[mod]
    btxt = mod if mod.isdigit() else mod.upper()
    ot = ix.off or "+0"
    sign, off = ot[0], ot[1:]
    if off.isdigit() and mod.isdigit():
        kp = (int(off) if sign == "+" else -int(off)) % B    # Python % is non-negative
        ktxt = str(kp)
    elif off.isdigit():
        # a literal offset against a PARAMETER block: the residue depends on the parameter's
        # value, so `-1` prints as `(SIDE - 1)`, never as the 2 it happens to be at SIDE = 3
        ktxt = off if sign == "+" else f"({btxt} - {off})"
    else:
        name = off.upper()
        ktxt = name if sign == "+" else f"({btxt} - {name})"    # a non-negative residue, symbolically
    extent = d.lanes[base][0]
    if B == extent:
        return base, f"(({var} + {ktxt}) % {btxt})"
    return base, f"(({var}/{btxt})*{btxt} + (({var}%{btxt} + {ktxt}) % {btxt}))"


def _axis_sv(d: Design, ix, extent: int, ext_txt: str) -> str:
    """One axis of a multi-axis lane reference as SV: a number; a genvar; `(r + k) % B` for a
    wrap over the whole axis (a ring), the block form otherwise; parameters by their localparam
    names, a literal offset against a parameter block kept symbolic (`(SIDE - 1)`)."""
    if ix.is_const:
        return str(ix.const)
    var = ix.var.lower()
    if ix.mod is None:
        return var + ix.off if ix.off else var
    mod = ix.mod
    B = int(mod) if mod.isdigit() else d.params[mod]
    btxt = mod if mod.isdigit() else mod.upper()
    ot = ix.off or "+0"
    sign, off = ot[0], ot[1:]
    if off.isdigit() and mod.isdigit():
        ktxt = str((int(off) if sign == "+" else -int(off)) % B)
    elif off.isdigit():
        ktxt = off if sign == "+" else f"({btxt} - {off})"
    else:
        name = off.upper()
        ktxt = name if sign == "+" else f"({btxt} - {name})"
    if B == extent:
        return f"(({var} + {ktxt}) % {btxt})"
    return f"(({var}/{btxt})*{btxt} + (({var}%{btxt} + {ktxt}) % {btxt}))"


def _sv_ref(lm) -> str:
    """`x[3]` / `x[i]` / `x[i-1]` / `x[TOP]` / `x[((i + 240) % 256)]` for a lane member.
    The index arrives already rendered by `_lane_member`, which knows the design's parameters."""
    return f"{lm[0]}[{lm[1]}]"


def _sv_ident(name: str) -> str:
    """A hoisting-safe identifier for a lane member: `y(0)` -> `y_0`."""
    return re.sub(r"[()+-]", "_", name).rstrip("_")


def wtxt(w) -> str:
    """A width as SV text: a number, a PARAMETER (upper-cased), or an expression over parameters."""
    if isinstance(w, int):
        return str(w)
    if isinstance(w, str):
        return w.lower() if is_var(w) else w.upper()      # a lane's loop variable is a genvar; a parameter a localparam
    if isinstance(w, tuple):
        if w[0] == "log2":
            return f"$clog2({wtxt(w[1])})"
        if w[0] in ("add", "sub", "mul") and len(w) == 3:
            return f"({wtxt(w[1])}{ {'add': '+', 'sub': '-', 'mul': '*'}[w[0]] }{wtxt(w[2])})"
    raise PrintError(f"not a width: {w!r}")


def _wdecl(w) -> str:
    """The SV type of a width."""
    if isinstance(w, tuple) and w and w[0] == "enum":
        return enum_tname(w[1])            # the enum typedef name, distinct from the net's
    if _isint(w):
        return "logic" if w == 1 else f"logic [{w - 1}:0]"
    return f"logic [{wtxt(w)}-1:0]"        # a parametric width


def _lane_decl(n_txt: str, w) -> str:
    """The SV type of a LANE (N members of width W) -- PACKED: `logic [N-1:0]` for 1-bit lanes (a
    vector: `req[i]`), `logic [N-1:0][W-1:0]` for wider ones (a packed 2-D: `q[i]` is an 8-bit
    element). Packed rather than an unpacked array (`logic [W-1:0] q [N]`) because that is the
    translator's LANE model (`val(q(I), V, T)` with the word<->lane bridge) -- the unpacked form is
    its MEMORY model (`addr`/cells), the shape `spram` prints to -- and because a lane read as a
    whole word (`{q[3], q[2], ..}`) is then free."""
    if isinstance(w, tuple) and w and w[0] == "enum":
        raise PrintError("an enum lane is not printable")
    dims = n_txt if isinstance(n_txt, tuple) else (n_txt,)
    n_dim = "".join(f"[{a}-1:0]" if not a.isdigit() else f"[{int(a) - 1}:0]" for a in dims)
    if _isint(w) and w == 1:
        return f"logic {n_dim}"
    return f"logic {n_dim}{_wdecl(w)[len('logic '):]}"


# ---------------------------------------------------------------------------------------------
# expressions
# ---------------------------------------------------------------------------------------------

class _Ctx:
    """Per-net SSA emission context: hoisted wires + their assigns."""

    def __init__(self, d: Design, lhs: str, axes_txt: tuple | None = None, gv: tuple | None = None):
        self.d, self.lhs, self.n = d, lhs, 0
        self.decls: list = []
        self.assigns: list = []
        self._memo: dict = {}
        # a MULTI-AXIS generate: a hoisted wire is declared at MODULE level as a lane over the
        # same axes and assigned per position, because a declaration inside a NESTED
        # for-generate body is one the translator refuses (2026-09-03); `decls` then go
        # before the generate block, not inside it
        self.axes_txt, self.gv = axes_txt, gv

    def wire(self, w, rhs: str) -> str:
        """A hoisted wire for `rhs` at width w (the same rhs at the same width is one wire)."""
        key = (str(w), rhs)
        if key in self._memo:
            return self._memo[key]
        name = f"{_sv_ident(self.lhs)}__e{self.n}"
        self.n += 1
        if self.axes_txt:
            dims = "".join(f"[{a}-1:0]" if not a.isdigit() else f"[{int(a) - 1}:0]" for a in self.axes_txt)
            elem = _wdecl(w)[len("logic "):]
            idx = "".join(f"[{g}]" for g in self.gv)
            self.decls.append(f"  logic {dims}{elem} {name};")
            self.assigns.append(f"    assign {name}{idx} = {rhs};")
            self._memo[key] = name + idx
            return name + idx
        self.decls.append(f"  {_wdecl(w)} {name};")
        self.assigns.append(f"  assign {name} = {rhs};")
        self._memo[key] = name
        return name

    def leaf(self, t) -> str:
        """The text of `t` as a leaf: a net name, a sized literal, a tag, or a hoisted wire.
        Boolean nodes and muxes INLINE with parentheses instead of hoisting a wire -- a
        1-bit && / || / ! has no width subtleties for the SSA machinery to guard, and an
        ite's arms keep their own handling; this is what turns `x__e0` chains into the
        readable `a[i] ? v : (hold)` shape (the regeneration run's naming requirement)."""
        if isinstance(t, tuple) and t and t[0] in (
                "logand", "logor", "lnot", "ite",
                "eq", "ne", "lt", "le", "gt", "ge", "slt", "sle", "sgt", "sge"):
            if t[0] != "logand" and t[0] != "logor" and t[0] != "lnot":
                return "(" + self.expr(t) + ")"
            if width_of(self.d, t) == 1:
                return "(" + self.expr(t) + ")"
        if isinstance(t, str):
            lm = _lane_member(self.d, t)
            if lm is not None:
                return _sv_ref(lm)
            return t
        if t[0] == "k":
            v, w = t[1], t[2]
            wide = isinstance(v, tuple) and v[0] == "str"            # a wide constant: ("str", digits)
            pexpr = not isinstance(v, int) and not wide              # a PARAMETER expression as the value
            if _isint(w) and pexpr:
                return f"{w}'({wtxt(v)})"                            # k(sub(ticks,1), 10) -> 10'(TICKS-1), not 10'dticks
            digits = v[1] if wide else str(v)
            if _isint(w):
                return f"{w}'d{digits}"
            if wide or (isinstance(v, int) and v >= 2 ** 31):
                raise PrintError(f"a wide constant at a parametric width ({term_to_str(t)}) is not printable")
            if isinstance(w, str) and (isinstance(v, int) or pexpr):
                # a constant OR a parameter expression at a named parametric width: the SV
                # size-cast, inline -- `COUNTWIDTH'(DEPTH-DEMANDRESERVE)`. Without the pexpr
                # half, a parameterized threshold fell back to a hoisted wire (and before
                # that, the generator baked the number -- the user's review, 2026-08-31)
                return f"{w.upper()}'({v if isinstance(v, int) else wtxt(v)})"
            return self.wire(w, wtxt(v) if not isinstance(v, int) else digits)   # sized by the wire's declaration
        if t[0] == "tag":
            return t[1]
        w = width_of(self.d, t)
        return self.wire(w, self.expr(t))

    def widened(self, t, w: int) -> str:
        """`t` as a leaf of EXACTLY width w (zero-extended through a wire when narrower) -- for the
        ops whose @func reads the sign bit at the op width."""
        tw = width_of(self.d, t)
        if isinstance(tw, tuple):
            raise PrintError(f"enum operand under an arithmetic op: {term_to_str(t)}")
        leaf = self.leaf(t)
        if tw == w:                        # ints, or the same parameter expression
            return leaf
        return self.wire(w, leaf)          # assign zero-extends

    def expr(self, t) -> str:
        """`t` as ONE SV operator applied to leaves (operands hoisted as needed)."""
        if isinstance(t, str) or t[0] in ("k", "tag"):
            return self.leaf(t)
        op = t[0]
        if op in BIN_OPS:
            return f"{self.leaf(t[1])} {BIN_OPS[op]} {self.leaf(t[2])}"
        if op == "ashr":
            w = t[3]
            return f"$signed({self.widened(t[1], w)}) >>> {self.leaf(t[2])}"
        if op in ("sidiv", "simod"):
            w = t[3]
            return f"$signed({self.widened(t[1], w)}) {'/' if op == 'sidiv' else '%'} $signed({self.widened(t[2], w)})"
        if op in ("slt", "sle", "sgt", "sge"):
            w = t[3]
            o = {"slt": "<", "sle": "<=", "sgt": ">", "sge": ">="}[op]
            return f"$signed({self.widened(t[1], w)}) {o} $signed({self.widened(t[2], w)})"
        if op == "bnot":
            return f"~{self.widened(t[1], t[2])}"
        if op == "neg":
            return f"-{self.widened(t[1], t[2])}"
        if op == "sext":
            f, w = t[2], t[3]
            a = self.widened(t[1], f)
            if w == f:
                return a
            if _isint(w) and _isint(f):
                return f"{{{{{w - f}{{{a}[{f - 1}]}}}}, {a}}}"
            return f"{{{{({wtxt(w)}-{wtxt(f)}){{{a}[{wtxt(f)}-1]}}}}, {a}}}"
        if op == "slc":
            lo, w = t[2], t[3]
            a = self.leaf(t[1])
            if _isint(lo) and _isint(w):
                return f"{a}[{lo + w - 1}:{lo}]" if w > 1 else f"{a}[{lo}]"
            return f"{a}[{wtxt(lo)}+{wtxt(w)}-1:{wtxt(lo)}]"
        if op == "bit":
            return f"{self.leaf(t[1])}[{wtxt(t[2])}]"
        if op == "cat":
            return f"{{{self.leaf(t[1])}, {self.leaf(t[3])}}}"
        if op == "mrd":                      # a flop-array read is an index, not a port
            return f"{t[1]}[{self.leaf(t[2])}]"
        if op == "pack":
            # A LANE IS ALREADY A PACKED VECTOR HERE (`logic [N-1:0] cap`), so its packed word is
            # simply its name -- `assign out_byte = cap;`. One line, and parametric because
            # nothing about it mentions the extent. The alternative the language forced before
            # this existed was a hand-written weighted sum, whose per-element weights made the
            # printed module lie about honouring its parameter (G20).
            return _sv_ident(t[1])
        if op == "lnot":
            return f"~{self.leaf(t[1])}"      # bitwise at 1 bit, same reason as BIN_OPS' & and |
        red = {"ror": "|", "rand": "&", "rxor": "^", "rnand": "~&", "rnor": "~|", "rxnor": "~^",
               "parity": "^"}
        if op in red:
            return f"{red[op]}{self.leaf(t[1])}"
        if op == "popcnt":
            return f"$countones({self.leaf(t[1])})"
        if op == "clz":
            raise PrintError(
                "clz has no print form yet. It is wired for AUTHORING and LINTING only, because there is no SystemVerilog construct for a leading-zero count -- lowering one means synthesising a priority encoder, a design decision nothing has needed yet. Until then a design that needs an LZC declares it as a CONTRACT-ONLY submodule and is proven from its contract; the print gives it as an interface stub. See notes/WORKLIST_SPEC2RTL.md.")
        if op == "ite":
            return f"{self.leaf(t[1])} ? {self.leaf(t[2])} : {self.leaf(t[3])}"
        raise PrintError(f"unknown operator {op}")


# ---------------------------------------------------------------------------------------------
# guarded rules -> always_comb
# ---------------------------------------------------------------------------------------------

def _rule_value_term(r: Rule):
    """The rule's head value as an expression term over the READ signals (steps folded in)."""
    env: dict = {}
    for s, v in r.reads:
        env[v] = s
    fmap = {"add": "add", "sub": "sub", "mul": "mul", "idiv": "idiv", "imod": "imod",
            "sidiv": "sidiv", "simod": "simod", "band": "and", "bor": "or", "bxor": "xor",
            "shl": "shl", "shr": "shr", "ashr": "ashr", "bnot": "bnot", "neg": "neg",
            "sext": "sext", "slc": "slc", "parity": "parity", "popcnt": "popcnt",
            "rand": "rand", "ror": "ror", "rxor": "rxor", "rnand": "rnand", "rnor": "rnor",
            "rxnor": "rxnor"}
    for st in r.steps:
        if st.func not in fmap:
            raise PrintError(f"@{st.func} in a comb rule is not printable (line {r.line})")
        op = fmap[st.func]
        args = []
        nval = {"add": 2, "sub": 2, "mul": 2, "idiv": 2, "imod": 2, "sidiv": 2, "simod": 2,
                "band": 2, "bor": 2, "bxor": 2, "shl": 2, "shr": 2, "ashr": 2, "bnot": 1,
                "neg": 1, "sext": 1, "slc": 1, "parity": 1, "popcnt": 1, "rand": 1, "ror": 1,
                "rxor": 1, "rnand": 1, "rnor": 1, "rxnor": 1}[st.func]
        wargs = st.args[nval:]
        w = wargs[-1] if wargs else None
        for a in st.args[:nval]:
            if isinstance(a, str):
                if a not in env:
                    raise PrintError(f"unbound {a} in step (line {r.line})")
                args.append(env[a])
            else:                                       # a constant operand: needs the op width
                if not isinstance(w, int):
                    raise PrintError(f"constant operand without a width in @{st.func} (line {r.line})")
                args.append(("k", a, w))
        env[st.var] = (op, *args, *wargs)
    v = r.value
    if isinstance(v, tuple) and v[0] == "var":
        return env[v[1]]
    return v                                            # int or tag label


def _rule_cond(ctx: "_Ctx", d: Design, r: Rule) -> str:
    """The arm's condition. A compare on an ENUM signal (a tag compare) is hoisted into its own
    1-bit wire: the translator lowers `state == idle` as a tag guard only when it stands alone
    (inside `&&` it would be handed to the @func cascade as a symbol and is refused, loudly)."""
    conds = []
    var_sig = {v: s for s, v in r.reads}
    lits = [(s, "==", c) for s, c in r.guards] + \
           [(var_sig[v], op if op != "=" else "==", c) for v, op, c in r.cmps]
    for s, op, c in lits:
        text = f"{s} {op} {_const_text(d, s, c)}"
        if isinstance(d.width_of(s), tuple):
            text = ctx.wire(1, text)
        conds.append(text)
    return " && ".join(f"({c})" if " " in c else c for c in conds) if len(conds) > 1 else conds[0]


def _const_text(d: Design, sig: str, c) -> str:
    w = d.width_of(sig)
    if isinstance(w, tuple):
        return str(c)                                    # a tag
    if isinstance(c, tuple):                             # ("str", digits)
        return f"{w}'d{c[1]}"
    return f"{w}'d{c}"


def _value_text(ctx: _Ctx, d: Design, head: str, v) -> str:
    w = d.width_of(head)
    if isinstance(v, int):
        return f"{w}'d{v}" if not isinstance(w, tuple) else str(v)
    if isinstance(v, str):
        return v                                         # a tag label
    return ctx.leaf(v)


# ---------------------------------------------------------------------------------------------
# totality certificate for guarded heads
# ---------------------------------------------------------------------------------------------

def _domain(d: Design, sig: str, rules: list):
    """The set of values `sig` ranges over for the coverage question of these rules, as clingo
    text, or None when it cannot be bounded (a wide signal under an ordering compare)."""
    w = d.width_of(sig)
    if isinstance(w, tuple):
        return "; ".join(l for l, _ in d.enums[w[1]])
    consts, ordered = set(), False
    for r in rules:
        for s, c in r.guards:
            if s == sig:
                consts.add(c)
        var_sig = {v: s for s, v in r.reads}
        for v, op, c in r.cmps:
            if var_sig[v] == sig:
                consts.add(c)
                if op in ("<", ">", "<=", ">="):
                    ordered = True
    if w <= 10 and (ordered or not consts or w <= 4):
        return f"0..{2 ** w - 1}"
    if ordered:
        return None
    ints = sorted(c for c in consts if isinstance(c, int))
    fresh = next(i for i in range(2 ** w) if i not in ints)   # one value none of the arms name
    return "; ".join(str(c) for c in ints + [fresh])


def totality_certificate(d: Design, head: str, clingo: str | None = None) -> bool:
    """True iff the head's arms are PROVEN to cover every valuation of the signals they guard on
    (each free over its domain, independently -- an over-approximation, so True is safe)."""
    from .lint import clingo_bin
    rules = [r for r in d.rules if r.head == head]
    sigs = sorted({s for r in rules for s, _ in r.guards} | {s for r in rules for s, _ in r.reads})
    prog = []
    for s in sigs:
        dom = _domain(d, s, rules)
        if dom is None:
            return False
        prog.append(f"{{ val({s}, V, 0) : V = ({dom}) }} = 1.")
    prog.append("time(clk, 0).")
    for r in rules:
        prog.append(r.text + ".")
    prog.append(f"gap :- not val({head}, _, 0).")
    prog.append(":- not gap.")
    with tempfile.TemporaryDirectory() as td:
        f = pathlib.Path(td) / "cover.lp"
        f.write_text("\n".join(prog) + "\n")
        p = subprocess.run([clingo or clingo_bin(), "-q", str(f), str(LIB_DIR / "aspfirst.lp")],
                           capture_output=True, text=True, timeout=120)
    return "UNSATISFIABLE" in p.stdout


# ---------------------------------------------------------------------------------------------
# the module
# ---------------------------------------------------------------------------------------------

def print_sv(d: Design, mode: str = "behav", src: str = "<design>.lp",
             certified: "set | None" = None) -> str:
    """The SystemVerilog text. `certified` = the guarded heads proven total (bare `else` allowed);
    None = compute the certificate for every guarded head now."""
    if mode not in ("cells", "behav"):
        raise PrintError(f"mode is cells or behav, not {mode!r}")
    if d.abstract_nets():
        raise PrintError(f"{len(d.abstract_nets())} net(s) still abstract -- not printable until every "
                         f"one is refined: {', '.join(d.abstract_nets())}")
    # (an abstract MODULE INSTANCE is printable: the parent instantiates it and print_hier emits an
    #  interface STUB for the module -- the RTL of this level alone, its children as black boxes)
    if certified is None:
        certified = {h for h in d.rule_heads() if totality_certificate(d, h)}
    for p in d.ports:
        if isinstance(p.width, tuple):
            raise PrintError(f"enum-typed port {p.name}: not printable yet (M5); use a logic port + a def")
    out: list = [HEADER.format(src=pathlib.Path(src).name)]
    # typedefs before the module (SV needs a type visible to the port list; internal only here)
    for e, ms in d.enums.items():
        w = enum_width(ms)
        body = ", ".join(f"{l} = {v}" for l, v in ms)
        out.append(f"typedef enum logic [{w - 1}:0] {{ {body} }} {enum_tname(e)};")
    if d.enums:
        out.append("")
    # header -- with the module's PARAMETERS when it has any (numeric params overridable, expression
    # params as localparams inside), every width printed symbolically from the raw (unresolved) design
    raw = d.raw
    pw = (lambda p: raw.port_w.get(p.name, p.width)) if raw is not None else (lambda p: p.width)
    nw = (lambda n: raw.net_w.get(n.name, n.width)) if raw is not None else (lambda n: n.width)
    is_member = lambda name: _lane_member(d, name) is not None
    # a lane's COUNT prints as written -- a parameter stays a parameter (`d [N]`, `i < N`), a number a number
    ln_n = (lambda name, N: wtxt(raw.lane_n.get(name, N))) if raw is not None else (lambda name, N: str(N))
    ln_w = (lambda name, W: raw.lane_w.get(name, W)) if raw is not None else (lambda name, W: W)

    def ln_n_axes(ln, N):
        """The extent text per axis (a tuple) for a lane with more than one axis, else ln_n(ln, N)."""
        ax = axes_of(d.lanes, ln)
        if len(ax) == 1:
            return ln_n(ln, N)
        raw_ax = raw.lane_axes.get(ln) if raw is not None else None
        return tuple(wtxt(raw_ax[k]) if raw_ax is not None else str(ax[k]) for k in range(len(ax)))
    ports = [f"  {p.direction} {_wdecl(pw(p))} {p.name}" for p in d.ports if not is_member(p.name)]
    for ln, (N, W, dr) in d.lanes.items():
        if dr:
            ports.append(f"  {dr} {_lane_decl(ln_n_axes(ln, N), ln_w(ln, W))} {ln}")
    numeric, hdr_derived, body_derived = _split_params(d, raw)
    if numeric or hdr_derived:
        out.append(f"module {d.name} #(")
        out.append(",\n".join([f"  parameter {k.upper()} = {v}" for k, v in numeric]
                              + [f"  localparam {k.upper()} = {wtxt(v)}" for k, v in hdr_derived]))
        out.append(") (")
    else:
        out.append(f"module {d.name} (")
    out.append(",\n".join(ports))
    out.append(");")
    for k, v in body_derived:
        out.append(f"  localparam {k.upper()} = {wtxt(v)};")
    # nets (a lane is ONE unpacked-array declaration; its members are not repeated)
    for n in d.nets:
        if not is_member(n.name):
            out.append(f"  {_wdecl(nw(n))} {n.name};")
    for ln, (N, W, dr) in d.lanes.items():
        if not dr:
            out.append(f"  {_lane_decl(ln_n_axes(ln, N), ln_w(ln, W))} {ln};")
    # a FLOP ARRAY is declared here, with the other declarations, not beside its always_ff: its
    # readers are `mrd(M, A)` expressions printed at their USE sites, which come first, and
    # SystemVerilog requires an array to be declared before it is read (Icarus: "Unable to bind
    # wire/reg/memory `tab[ra]' ... Check for declaration after use")
    for i in d.insts:
        if i.cell == "farray":
            # RAW iparams, exactly as _inst_sv's ip() reads them: this declaration printed from
            # the RESOLVED values once, so a parametric module's storage came out as fixed
            # numbers -- parameters that were real everywhere else and fake here (the user's
            # catch on the v2 FIFO: `logic [7:0] storage [0:3]` under `#(parameter DEPTH,
            # WIDTH)` -- an override would have silently built wrong hardware).
            gp = (lambda k: d.raw.iparams.get((i.name, k), i.iparams.get(k))) if d.raw is not None \
                else (lambda k: i.iparams.get(k))
            fw, fdep = gp("width"), gp("depth")
            fhi = f"{fw - 1}" if _isint(fw) else f"{wtxt(fw)}-1"
            ftop = f"{fdep - 1}" if _isint(fdep) else f"{wtxt(fdep)}-1"
            out.append(f"  logic [{fhi}:0] {i.name} [0:{ftop}];")
    out.append("")
    # combinational defs (a lane member inside a lane def's WINDOW is printed by that generate below; a
    # member outside every window -- the boundary lane of a chain, `def(y(0), ...)` -- is a plain assign)
    import itertools as _it
    covered = set()
    for ln, iv, _e, lo, hi in d.lane_defs:            # the members a generate block prints
        if isinstance(iv, tuple):
            covered |= {member(ln, *idx) for idx in _it.product(*(range(a, b + 1) for a, b in zip(lo, hi)))}
        else:
            covered |= {f"{ln}({i})" for i in range(lo, hi + 1)}
    for n in d.def_order:
        if n in covered:
            continue
        ctx = _Ctx(d, n)
        term = raw.defs[n] if raw is not None and n in raw.defs else d.defs[n]
        rhs = ctx.expr(term)
        out.extend(ctx.decls)
        out.extend(ctx.assigns)
        lm = _lane_member(d, raw.def_targets.get(n, n) if raw is not None else n)
        w = width_of(d, n)
        if isinstance(w, tuple) and w and w[0] == "enum" and isinstance(term, tuple) and term[0] == "ite":
            rhs = f"{enum_tname(w[1])}'({rhs})"   # an enum-typed ternary needs an explicit cast (Icarus: "requires an explicit cast")
        out.append(f"  assign {_sv_ref(lm) if lm else n} = {rhs};")
    # lane defs: one generate block per lane, the def once with the index as the genvar, the bounds from the
    # WINDOW (`x(I-1)` in the body starts it at 1; `x(I+1)` ends it at N-2 -- printed `i < N-1` when N is a param)
    # RELATED LANES SHARE ONE GENERATE BLOCK (the regeneration run's grouping
    # requirement): consecutive lane defs with the same index range -- a slot's CAM
    # nets, a run of chains, the M1 next-value cluster -- print inside one block,
    # labelled by their first member, instead of one block per net.
    runs, cur = [], None
    for ln, ivs, e, los, his in [x for x in d.lane_defs if isinstance(x[1], tuple)]:
        # a MULTI-AXIS lane def: one nested generate per def, the window per axis (2026-09-03)
        ax = axes_of(d.lanes, ln)
        ax_txt = ln_n_axes(ln, d.lanes[ln][0])
        heads = []
        for k, (iv, lo, hi) in enumerate(zip(ivs, los, his)):
            n_txt = ax_txt[k]
            cut = ax[k] - 1 - hi
            hi_txt = str(hi + 1) if n_txt.isdigit() else (f"{n_txt}-{cut}" if cut else n_txt)
            heads.append(f"for (genvar {iv.lower()} = {lo}; {iv.lower()} < {hi_txt}; {iv.lower()}++)")
        ctx = _Ctx(d, ln, axes_txt=tuple(ax_txt), gv=tuple(iv.lower() for iv in ivs))
        rhs = ctx.expr(raw.lane_defs.get(ln, e) if raw is not None else e)
        out.extend(ctx.decls)                                # module-level lanes, before the block
        out.append(f"  generate {' '.join(heads)} begin : g_{ln}")
        out.extend(ctx.assigns)
        out.append(f"    assign {ln}{''.join(f'[{iv.lower()}]' for iv in ivs)} = {rhs};")
        out.append("  end endgenerate")
    for ln, iv, e, lo, hi in d.lane_defs:
        if isinstance(iv, tuple):
            continue
        N = d.lanes[ln][0]
        i = iv.lower()
        cut = N - 1 - hi
        n_txt = ln_n(ln, N)
        hi_txt = str(hi + 1) if n_txt.isdigit() else (f"{n_txt}-{cut}" if cut else n_txt)
        key = (i, lo, hi_txt)
        if cur is None or cur[0] != key:
            cur = (key, [])
            runs.append(cur)
        cur[1].append((ln, e))
    for (i, lo, hi_txt), members in runs:
        out.append(f"  generate for (genvar {i} = {lo}; {i} < {hi_txt}; {i}++) "
                   f"begin : g_{members[0][0]}")
        for ln, e in members:
            ctx = _Ctx(d, ln)
            rhs = ctx.expr(raw.lane_defs.get(ln, e) if raw is not None else e)
            out.extend("  " + x for x in ctx.decls)
            out.extend("  " + x for x in ctx.assigns)
            out.append(f"    assign {ln}[{i}] = {rhs};")
        out.append("  end endgenerate")
    # guarded rules
    for h in d.rule_heads():
        rules = [r for r in d.rules if r.head == h]
        ctx = _Ctx(d, h)
        arms = [(_rule_cond(ctx, d, r), _value_text(ctx, d, h, _rule_value_term(r))) for r in rules]
        out.extend(ctx.decls)
        out.extend(ctx.assigns)
        out.append("  always_comb begin")
        for i, (c, v) in enumerate(arms):
            last = i == len(arms) - 1
            if i == 0:
                out.append(f"    if ({c}) {h} = {v};")
            elif last and h in certified:
                out.append(f"    else {h} = {v};   // total: proven by the totality certificate")
            else:
                out.append(f"    else if ({c}) {h} = {v};")
        if h not in certified:
            out.append(f"    // no totality certificate for {h}: no default arm on purpose -- an "
                       f"uncovered case is a translation-time PROBLEM, not a latch")
        out.append("  end")
    # state (lane instances: one generate block, the cell once with the index as the genvar)
    is_lane_inst = lambda name: (parse_ref(name) is not None and parse_ref(name).base in d.lane_insts)
    for i in d.insts:
        if is_lane_inst(i.name):
            continue
        out.append("")
        out.extend(_inst_sv(d, i, mode))
    # the slot FLOPS share one generate block per count, for the same grouping reason
    inst_runs, cur = [], None
    for u, (cell, N) in d.lane_insts.items():
        if u in getattr(d, "inst_axes", {}):
            # a MULTI-AXIS instance lane: one nested generate, the cell once, each lane pin the
            # member at the same position (2026-09-03)
            ax = d.inst_axes[u]
            raw_ax = raw.lane_axes.get(u) if raw is not None else None
            gv = ["i", "j", "k", "l"][:len(ax)]
            heads = []
            for k_, ext in enumerate(ax):
                n_txt = wtxt(raw_ax[k_]) if raw_ax is not None else str(ext)
                heads.append(f"for (genvar {gv[k_]} = 0; {gv[k_]} < {n_txt}; {gv[k_]}++)")
            out.append("")
            out.append(f"  generate {' '.join(heads)} begin : g_{u}")
            first = next(x for x in d.insts if x.name == member(u, *([0] * len(ax))))
            pins = {}
            for pn, net in first.pins.items():
                lm = _lane_member(d, net)
                pins[pn] = f"{lm[0]}{''.join(f'[{g}]' for g in gv)}" if lm is not None else net
            rolled = type(first)(u, cell, pins, dict(first.iparams), dict(first.mparams))
            out.extend("  " + x for x in _inst_sv(d, rolled, mode))
            out.append("  end endgenerate")
            continue
        key = ln_n(u, N)
        if cur is None or cur[0] != key:
            cur = (key, [])
            inst_runs.append(cur)
        cur[1].append((u, cell, N))
    for n_txt, members in inst_runs:
        out.append("")
        out.append(f"  generate for (genvar i = 0; i < {n_txt}; i++) "
                   f"begin : g_{members[0][0]}")
        for u, cell, N in members:
            first = next(x for x in d.insts if x.name == f"{u}(0)")
            pins = {}
            for pn, net in first.pins.items():
                lm = _lane_member(d, net)
                pins[pn] = f"{lm[0]}[i]" if lm is not None else net
            rolled = type(first)(u, cell, pins, dict(first.iparams), dict(first.mparams))
            out.extend("  " + x for x in _inst_sv(d, rolled, mode))
        out.append("  end endgenerate")
    out.append("endmodule")
    return "\n".join(out) + "\n"


def _inst_sv(d: Design, i, mode: str) -> list:
    # a scalar instance's pin on a lane MEMBER (`pin(u, d, q(3))`) prints as `q[3]`
    p = {k: (_sv_ref(_lane_member(d, v)) if _lane_member(d, v) else v) for k, v in i.pins.items()}
    ip = (lambda k: d.raw.iparams.get((i.name, k), i.iparams[k])) if d.raw is not None else (lambda k: i.iparams[k])
    if i.cell not in ("ff", "arff", "lata", "spram", "farray"):
        # an AUTHORED module: a plain instantiation (with its parameter overrides); the module itself is
        # printed separately (print_hier)
        conns = ", ".join(f".{port}({net})" for port, net in p.items())
        ov = (" #(" + ", ".join(f".{k.upper()}({v})" for k, v in i.mparams.items()) + ")") if i.mparams else ""
        return [f"  {i.cell}{ov} {i.name} ({conns});"]
    if i.cell == "spram":
        w, depth = ip("width"), ip("depth")
        if not (_isint(w) and _isint(depth)):
            return [f"  logic [{wtxt(w)}-1:0] {i.name} [0:{wtxt(depth)}-1];",
                    f"  always_ff @(posedge {p['clk']}) if ({p['we']}) {i.name}[{p['wa']}] <= {p['wd']};",
                    f"  assign {p['rd']} = {i.name}[{p['ra']}];"]
        return [f"  logic [{w - 1}:0] {i.name} [0:{depth - 1}];",
                f"  always_ff @(posedge {p['clk']}) if ({p['we']}) {i.name}[{p['wa']}] <= {p['wd']};",
                f"  assign {p['rd']} = {i.name}[{p['ra']}];"]
    if i.cell == "farray":
        # an array of REGISTERS: the write port, and an async reset that clears EVERY cell (the shape
        # an SRAM cannot have). Its readers are `mrd(M, A)` expressions printed at their use sites.
        w, depth = ip("width"), ip("depth")
        hi = f"{w - 1}" if _isint(w) else f"{wtxt(w)}-1"
        top = f"{depth - 1}" if _isint(depth) else f"{wtxt(depth)}-1"
        _ = (hi, top)                       # the DECLARATION is emitted with the other nets, above
        rst = p.get("rstL")
        if rst is None:
            return [f"  always_ff @(posedge {p['clk']}) if ({p['we']}) {i.name}[{p['wa']}] <= {p['wd']};"]
        rv = ip("reset_value")
        return [f"  always_ff @(posedge {p['clk']} or negedge {rst})",
                f"    if (!{rst}) for (int unsigned gi = 0; gi <= {top}; gi++) {i.name}[gi] <= {wtxt(rv)};",
                f"    else if ({p['we']}) {i.name}[{p['wa']}] <= {p['wd']};"]
    if i.cell == "lata":
        # the classic inferred-latch idiom: transparent while en is high, holds otherwise --
        # the shape sv2asp's allow_latches path and Icarus both handle (latch_demo's family).
        # The round trip's generated manifest sets allow_latches when a design carries one.
        return [f"  always @* if ({p['en']}) {p['q']} = {p['d']};"]
    q_w = d.width_of(i.pins["q"])
    enum_reg = isinstance(q_w, tuple)
    if i.cell == "ff":
        if mode == "cells" and not enum_reg:
            return [f"  FF #(.WIDTH({wtxt(ip('width'))})) {i.name} "
                    f"(.clk({p['clk']}), .en({p['en']}), .d({p['d']}), .q({p['q']}));"]
        if d.defs.get(p['en']) == ("k", 1, 1):
            return [f"  always_ff @(posedge {p['clk']})",
                    f"    {p['q']} <= {p['d']};"]
        return [f"  always_ff @(posedge {p['clk']})",
                f"    if ({p['en']}) {p['q']} <= {p['d']};"]
    if i.cell == "arff":
        rv = i.iparams["reset_value"]
        w = ip("width")
        if mode == "cells" and not enum_reg:
            return [f"  ARFF #(.WIDTH({wtxt(w)}), .RESET_VALUE({rv})) {i.name} "
                    f"(.clk({p['clk']}), .en({p['en']}), .rstL({p['rstL']}), .d({p['d']}), .q({p['q']}));"]
        if enum_reg:
            # AN ENUM REGISTER RESETS TO A MEMBER, not to its number: SystemVerilog enums are
            # strongly typed, and `st <= 2'd0` into `st_t st` is "requires an explicit cast"
            # (iverilog). The value the author wrote is looked up among the members; a value
            # no member carries is refused by name, because a reset to a non-member is an
            # authoring error the type exists to catch (G21, 2026-09-02).
            members = d.enums.get(q_w[1], [])
            hit = [l for l, v in members if v == rv]
            if isinstance(rv, str) and any(l == rv for l, _ in members):
                rv_t = rv                                   # already a member name
            elif hit:
                rv_t = hit[0]
            else:
                raise PrintError(f"{i.name}: reset_value {rv!r} is not a member of enum "
                                 f"{q_w[1]} ({', '.join(l for l, _ in members)})")
        elif _isint(w):
            rv_t = f"{w}'d{rv}"
        else:
            rv_t = "'0" if rv == 0 else f"{wtxt(w)}'({rv})"          # a parametric width: SV fill / size cast
        en = p['en']
        always_on = d.defs.get(en) == ("k", 1, 1)
        tail = (f"    else {p['q']} <= {p['d']};" if always_on
                else f"    else if ({en}) {p['q']} <= {p['d']};")
        return [f"  always_ff @(posedge {p['clk']} or negedge {p['rstL']})",
                f"    if (!{p['rstL']}) {p['q']} <= {rv_t};",
                tail]
    raise PrintError(f"{i.name}: unknown cell {i.cell}")


CELLS_SIM = LIB_DIR / "cells_sim.sv"


def stub_sv(module_path) -> str:
    """An INTERFACE STUB for an authored module: its port list and an empty body -- the shape of
    `examples/rtl2asp/primitives_demo/stubs/cells.sv`. What a parent's RTL is printed against when
    the module is still abstract (contract-only): the parent is real RTL, the child a black box the
    user builds later against the same contract."""
    from .load import load
    d = load(module_path)
    pw = (lambda p: d.raw.port_w.get(p.name, p.width)) if d.raw is not None else (lambda p: p.width)
    ports = ",\n".join(f"  {p.direction} {_wdecl(pw(p))} {p.name}" for p in d.ports)
    numeric, hdr_derived, _body = _split_params(d, d.raw)
    plist = ([f"  parameter {k.upper()} = {v}" for k, v in numeric]
             + [f"  localparam {k.upper()} = {_wtxt(v)}" for k, v in hdr_derived])
    hdr = (f"module {d.name} #(\n" + ",\n".join(plist) + "\n) (\n") if plist else f"module {d.name} (\n"
    return (f"// STUB (interface only) of {d.name}: abstract in the parent -- its contract "
            f"({module_path.stem}.contract.lp) is what the parent was proven against.\n"
            f"{hdr}{ports}\n);\nendmodule\n")


def print_hier(path, mode: str = "behav") -> str:
    """The design at `path` and every authored module it (transitively) instantiates, each as its
    own SystemVerilog module -- children first, so a single file compiles. A module that is
    ABSTRACT in its parent is emitted as an interface stub (the parent's RTL alone, the child a
    black box); abstract NETS refuse."""
    from .compose import compose, resolve_module
    from .load import load
    comp = compose(path)
    if comp.design.abstract_nets() and not any(ab for _, _, ab in comp.tree):
        raise PrintError(f"still abstract: {', '.join(comp.design.abstract_nets())} -- refine before printing")
    texts, seen = [], set()

    def emit(p, top: bool):
        d = load(p)
        if d.abstract_nets():
            raise PrintError(f"{p.name}: abstract net(s) {', '.join(d.abstract_nets())} -- refine before printing")
        abstract_insts = set(d.abstract_insts())
        for i in d.module_insts():
            if i.cell in seen:
                continue
            seen.add(i.cell)
            mp = resolve_module(i.cell, pathlib.Path(p).parent)
            if i.name in abstract_insts:
                texts.append(stub_sv(mp))
            else:
                emit(mp, False)
        texts.append(print_sv(d, mode=mode, src=str(p)))
    emit(pathlib.Path(path), True)
    return "\n".join(texts)
